### PR TITLE
correct bug where "What's New" dialog was always displayed on app start

### LINKED ISSUE #65: "what's new" dialog appears every time the app is launched
doesn't seem to be intentional.. once the user has read/dismissed it, it becomes a hindrance to have it at every app launch

### PR DESCRIPTION
**Pull request by popz73**
fixes #65

### CODE REVIEW

File: app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt [hunk 1]
```diff
@@ -1,14 +1,35 @@
...
+
     val whatsNewText = currentText
 
     fun textShown() {
-        PersistenceManager.lastWhatsNewText = currentText
+        PersistenceManager.lastWhatsNewText = hashString(currentText)
+    }
+
+    private fun hashString(text: String): String {
+        return toHex(MessageDigest.getInstance("MD5").digest(text.toByteArray(Charsets.UTF_8)))
```
Comment (acristescu) [inline app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt:16]: what I think you're trying to achieve with `toHex()` is basically `.fold("", { str, it -> str + "%02x".format(it) })` isn't it? If so, please replace it with that.

File: app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt [hunk 2]
```diff
@@ -1,14 +1,35 @@
 package io.zenandroid.onlinego.utils
+import java.security.MessageDigest
 
 object WhatsNewUtils {
 
     val shouldDisplayDialog: Boolean
-            get() = PersistenceManager.lastWhatsNewText != currentText
-//            get() = PersistenceManager.lastWhatsNewText != null && PersistenceManager.lastWhatsNewText != currentText
+        get() = PersistenceManager.lastWhatsNewText != hashString(currentText)
```
Comment (acristescu) [inline app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt:7]: The reason I did not remove that line is that in the future I do not want everybody to see the whats new when they install the app, but I did want to see it last time (because of the big update). Hence, moving forward, I would like to have it `PersistenceManager.lastWhatsNewText != null &&  PersistenceManager.lastWhatsNewText != hashString(currentText)`. Can we also please rename the field now so that it's obvious it's a hash?

Comment (popz73) [reply app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt:7]: ok

File: app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt (hunk 1 above)
Comment (popz73) [reply app/src/main/java/io/zenandroid/onlinego/utils/WhatsNewUtils.kt:16]: nice one!

**Comment by popz73** [comment]
ready
